FROM node:20-alpine

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile

COPY . .

# Garante que, mesmo após copiar o código completo, dependências novas sejam resolvidas
RUN pnpm install

RUN pnpm build

CMD ["node", "dist/main"]
